### ISSUE TITLE
no stage1

### ISSUE THREAD

**Issue by Zhang-JnQn** [niccolo246/Advanced_nnUNet#1]
hi,
I use inception for training and errors comes like "FileNotFoundError: [Errno 2] No such file or directory: '/root/autodl-tmp/nnUNetFrame/DATASET/nnUNet_preprocessed/xxxxxxxxx/nnUNetData_plans_v2.1_stage1". 
I check the folder and only "nnUNetData_plans_v2.1_2D_stage0" exists, no stage1 folder.
Do you know how to solve it?

**Comment by Zhang-JnQn** [comment]
my fault, I miss one operation

**Comment by niccolo246** [comment]
Hi, wondering for future reference, which was the operation missed?
